import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

/**
 * Unit tests for the JS port of `rule_ids.compute_rule_id` +
 * `_rule_id_payload` used by the annotator.
 *
 * The JS implementation must be byte-equivalent with the Python reference.
 * The canonical check is against `fixtures/rule_id_fixtures.json`, which is
 * regenerated by the upstream Python reference implementation.
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);

const hashModulePath = path.resolve(__dirname, '../extract_field_hash.js');
const fixturePath = path.resolve(__dirname, 'fixtures/rule_id_fixtures.json');

const hashModule = require(hashModulePath);
const fixture = JSON.parse(fs.readFileSync(fixturePath, 'utf-8'));

const {
    canonicalRuleSignature,
    computeRuleId,
    extractFieldIdPayload,
    assignExtractFieldIds,
} = hashModule;

describe('canonicalRuleSignature', () => {
    it('matches Python json.dumps(sort_keys, compact, ensure_ascii=False) byte-for-byte', () => {
        for (const c of fixture.cases) {
            const got = canonicalRuleSignature(c.payload);
            assert.equal(
                got,
                c.signature,
                `signature mismatch for case ${c.name}`,
            );
        }
    });

    it('strips the `id` key before signing', () => {
        const rule = {
            type: 'extract_field',
            id: 'abc123',
            field_path: 'foo',
            source_bbox_index: null,
            expected_value: 'bar',
            verified: true,
            tags: [],
        };
        const withoutId = { ...rule };
        delete withoutId.id;
        assert.equal(
            canonicalRuleSignature(rule),
            canonicalRuleSignature(withoutId),
        );
    });
});

describe('computeRuleId', () => {
    it('matches the Python-generated id for every fixture case', async () => {
        for (const c of fixture.cases) {
            const got = await computeRuleId(c.payload, fixture.hash_len);
            assert.equal(got, c.id, `id mismatch for case ${c.name}`);
        }
    });

    it('uses NUL byte (0x00) as the page_prefix separator', async () => {
        // A rule with an empty page prefix hashes ` {signature}` (NUL byte).
        // Any other separator would cause divergence from Python. Assert by
        // cross-checking against Python's fixture output.
        const payload = fixture.cases[0].payload;
        const id = await computeRuleId(payload, fixture.hash_len);
        assert.equal(id, fixture.cases[0].id);
        // Manual SHA check: sha256("\u0000" + signature).slice(0, 16)
        const signature = canonicalRuleSignature(payload);
        const nodeCrypto = require('node:crypto');
        const expected = nodeCrypto
            .createHash('sha256')
            .update('\u0000' + signature, 'utf-8')
            .digest('hex')
            .slice(0, fixture.hash_len);
        assert.equal(id, expected);
    });
});

describe('extractFieldIdPayload', () => {
    it('extracts the first bbox source_bbox_index when present', () => {
        const rule = {
            type: 'extract_field',
            id: 'ignored',
            field_path: 'line_items[0].description',
            expected_value: 'Widget',
            bboxes: [
                { page: 1, bbox: [0, 0, 0.1, 0.1], source_bbox_index: 17 },
                { page: 1, bbox: [0, 0.2, 0.1, 0.1], source_bbox_index: 18 },
            ],
            verified: false,
            tags: ['benchmark_fixture', 'stray_evidence'],
        };
        const payload = extractFieldIdPayload(rule);
        assert.deepEqual(payload, {
            type: 'extract_field',
            field_path: 'line_items[0].description',
            source_bbox_index: 17,
            expected_value: 'Widget',
            verified: false,
            tags: ['benchmark_fixture', 'stray_evidence'],
        });
    });

    it('returns null source_bbox_index when bboxes is empty', () => {
        const rule = {
            type: 'extract_field',
            field_path: 'scalar',
            expected_value: null,
            bboxes: [],
            verified: true,
            tags: [],
        };
        assert.equal(extractFieldIdPayload(rule).source_bbox_index, null);
    });

    it('defaults missing verified to true (matches Python schema default)', () => {
        // The Python Pydantic model sets `verified: bool = True` in
        // schema.py, and audit_annotator_roundtrip.py uses
        // `bool(rule.get("verified", True))`. JS must match so rule ids
        // hash identically across implementations.
        const rule = { type: 'extract_field', field_path: 'x' };
        const payload = extractFieldIdPayload(rule);
        assert.equal(payload.verified, true);
        assert.deepEqual(payload.tags, []);
        assert.equal(payload.expected_value, null);
        assert.equal(payload.source_bbox_index, null);
    });

    it('respects explicit verified=false', () => {
        const rule = { type: 'extract_field', field_path: 'x', verified: false };
        assert.equal(extractFieldIdPayload(rule).verified, false);
    });

    it('respects explicit verified=true', () => {
        const rule = { type: 'extract_field', field_path: 'x', verified: true };
        assert.equal(extractFieldIdPayload(rule).verified, true);
    });
});

describe('assignExtractFieldIds', () => {
    it('assigns the base id when there are no collisions', async () => {
        const rules = fixture.cases
            .slice(0, 3)
            .map((c) => ({ ...c.payload, bboxes: [] }));
        await assignExtractFieldIds(rules, fixture.hash_len);
        const ids = rules.map((r) => r.id);
        // Every id must be a base id (no "{counter:03d}-" prefix).
        for (const id of ids) {
            assert.match(id, /^[0-9a-f]+$/);
        }
        // All unique.
        assert.equal(new Set(ids).size, ids.length);
    });

    it('prefixes colliding rules with {counter:03d}- in signature order', async () => {
        const payloads = fixture.collision.assignments.map((a) => ({
            ...a.rule,
            bboxes: [],
        }));
        const expectedIds = fixture.collision.assignments.map((a) => a.id);
        await assignExtractFieldIds(payloads, fixture.hash_len);
        assert.deepEqual(payloads.map((r) => r.id), expectedIds);
    });

    it('is idempotent: running twice produces identical ids', async () => {
        const rules = fixture.cases
            .slice(0, 5)
            .map((c) => ({ ...c.payload, bboxes: [] }));
        await assignExtractFieldIds(rules, fixture.hash_len);
        const first = rules.map((r) => r.id);
        await assignExtractFieldIds(rules, fixture.hash_len);
        const second = rules.map((r) => r.id);
        assert.deepEqual(first, second);
    });

    it('does nothing on empty input', async () => {
        await assignExtractFieldIds([], fixture.hash_len);
        // (no throw = pass)
    });
});
